[package]
name = "example-gui-app"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
astrelis-framework.workspace = true
tracing.workspace = true
rand = "0.9.1"
