[package]
name = "astrelis-render"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
description = "Astrelis Core Rendering Module"

[features]
# Enable mock GPU types for testing
mock = ["astrelis-test-utils/mock"]

[dependencies]
tracing.workspace = true
astrelis-core.workspace = true
astrelis-test-utils.workspace = true
astrelis-winit.workspace = true
wgpu.workspace = true
pollster.workspace = true
bytemuck.workspace = true
bitflags.workspace = true
