[package]
name = "astrelis-winit"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
description = "Astrelis integration for winit"

[dependencies]
astrelis-core.workspace = true

tracing.workspace = true
winit.workspace = true

bitflags.workspace = true
