[package]
name = "astrelis-text"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[features]
default = ["asset"]
asset = ["dep:astrelis-assets"]

[dependencies]
astrelis-core.workspace = true
astrelis-render.workspace = true
astrelis-assets = { workspace = true, optional = true }

# Text rendering
cosmic-text.workspace = true

# Utilities
bytemuck.workspace = true
tracing.workspace = true
sys-locale.workspace = true
fxhash = "0.2.1"

[dev-dependencies]
astrelis-winit.workspace = true
astrelis-assets.workspace = true
pollster.workspace = true
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "text_rendering"
harness = false

[[bench]]
name = "text_measurement"
harness = false

[[bench]]
name = "text_pipeline"
harness = false
