[package]
name = "example-roguerun"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
astrelis-framework.workspace = true
tracing.workspace = true
